apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-release-16-py-prod
  namespace: tssc-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/test-release-16-py/overlays/prod
    repoURL: https://github.com/prietyc123-qe-org/test-release-16-py-gitops.git
    targetRevision: main
  destination:
    namespace: tssc-app-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: tssc-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
